name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: tytydraco/android-public-build@main
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
